name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f539bd20ea6fe0ec88ba9e6ac2ae77aceb15662db7c077275d6b8e2c5667b34b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
