name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dc1c48367b4773e691de0dfd0d2a0dd646b6339d0e884a94d52df3a4ca59891"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
