name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c827a5a7dc41120cf03678c0e836f6d19cf96db7dd0d5ba6d259bb66a672336"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
