name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29901926a9f7b34ddf5e9a4f51d1a39fc98f29aaab0a7dc4b8861ddb2c55f180"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
