name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f124c4ead20ee278a40f9e51cce6109ff2101813d246e60b76950e0b1492f00c"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
