name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad80c59f98ca493118261f077809bad8b02679aa0fb43e082dbe9525fc3fe169"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
