name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89329bb6a3a89f4ad7f7860b222a0701c32ed51f6663f61dbdb00c8a59a060ca"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
