name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242d8fbf33240b571ff6342da65178d3e45bd4744db5688239d53dbde944e165"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
