name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a645d622aa4dfec04d53d3a1d6c2bff0d9dc9dd41635030fa6ebeb42b7a1407d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
