name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e8815758e9e6fd4878ab57e9fffb900648a6828f9ec2124ef4adabefe660ef5"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
