name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04e7d563d0e6e7bd3514e0150471bd302f517e97839f918a6279e7fff637e681"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
