name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b092e29e033606883a05a3ec3d58724c1e090b28915eac2ff97e77ad303d0f2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
