name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd36a2f6339b89a5a7b8f506359b8e9aa05e6512402228135829d1ba4baf4c8a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
