name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d539e831eeb287ab7ece2c5e30983eea10a67f1d32a7a088d13bdf9c25c442"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
