name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5851f99de27aa1b4293e81aeefdc1130fd26aa3029fda203fffaa964a762986c"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
