name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9dbe0ecc7cb95f9c60e7a28dc3f6eeeb7b7d3867ecf312c3410702cf574ab3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
