name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d31057d32b56d1e04471b0a92b789c5fb307086cf7d55db47e7fdbdb06e66e4d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
