name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c581c40d769cfbc4efac44ae71bdf8344c0165b1a03af868686f9aa7a6a323ca"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
