name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec5de23a8aebd2581a449a6746159b418e5baf5e3c05bcd8b339982fd5c90fa"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
