name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a9632b88fde4138c57f0a86a252e535f4bcd0664795f03cd6000d1f089a7323"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
