name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a47d417f1aafa2404d5867d824819cc0c647d7ff33a500e0dbc76449ffc91286"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
