name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4011afda51397a0339c1dc7680bcea860c7ffef3af1e51c80ed177061c38fb67"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
