name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113f8da066fc14d9dc03f6b5fe2ff80f7661a0ec28adeeb03231ee4dac219fc2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
