name = "Moria"
author = "obnyis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a320fec4dc8eef60b4e14eba4a15d7a3cd5dd8b190c16e9664cfd95abccb5a6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
