on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  packwiz-refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - name: Setup packwiz
        run: |
          go install github.com/packwiz/packwiz@latest

      - name: Check for files that are out of sync with the index
        run: |
          packwiz refresh

      - if: github.event_name == 'push' && github.ref_name == 'main'
        uses: git-actions/set-user@v1

      - name: Commit/push if there is a diff
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          if ! git diff --exit-code; then
            git add .
            git commit -m "chore: fixup packwiz hashes $GITHUB_SHA [ci skip]"
            git push origin main
          fi